### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 666damn** [UBISOFT-1/AnonymousPAK-DDoS#2]
Which python version should I use and do I need to make it exe to run in windows?

**Comment by UBISOFT-1** [comment]
Hey, @666damn! In order to go ahead and start using it to test on your own websites, you first need to go ahead and download python3 from python.org or from Microsoft Store. Then in the installation process add pip and python 3.9 to Path must also be selected. After that you can go ahead and download Go from https://golang.org/doc/install.

With that done, you can do this in the terminal.

```
cd AnonymousPAK-DDoS/
python3 Install_Dependancies.py
```

Also, make sure to go ahead and follow the instructions in the README.md file.

Hope that Helps!

**Comment by UBISOFT-1** [comment]
I am going to record a quick video, demo on how to do that on Windows here @666damn so its a bit easier for you as well. Whilst I do that you can try running it by following steps as shown above. Its just installing Python and Golang.
